# Generated by Django 2.0.7 on 2018-08-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcha', '0011_auto_20180820_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='star',
        ),
    ]
