# Generated by Django 2.0.7 on 2018-08-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcha', '0012_remove_comment_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='pubDate',
            field=models.TextField(blank=True, null=True, verbose_name='제작년도'),
        ),
    ]
